# 01. Vectors, Points, and Coordinate Systems

## 01.01 Why Graphics Starts with Vectors

Computer graphics repeatedly works with points, directions, displacements, normals, camera axes, light directions, and triangle edges.

These objects are naturally represented using vectors.

A 3D point can be written as:

$$
p = 
\begin{bmatrix}
2 \\
1 \\
3
\end{bmatrix}
$$

A direction vector can be written as:

$$
v =
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

Moving point p along direction v by 5 units gives:

$$
p' = p + 5v
$$

Therefore:

$$
p'=
\begin{bmatrix}
2 \\
1 \\
3
\end{bmatrix}+
5
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}=
\begin{bmatrix}
7 \\
1 \\
3
\end{bmatrix}
$$

## 01.02 Points vs Vectors

A point represents a position.

A vector represents a direction, displacement, velocity, normal, or light direction.

A point plus a vector gives another point:

$$
p'=p+v
$$

Two points subtracted from each other give a vector:

$$
v=p_2-p_1
$$

Vector plus vector gives another vector:

$$
w=u+v
$$

Scalar times vector gives another vector:

$$
w=av
$$

But point plus point usually has no direct geometric meaning.


## 01.03 Vector Addition and Scalar Multiplication

核心命题：向量加法和标量乘法满足线性结构

In [9]:
import numpy as np

# 点：表示空间中的位置
p = np.array([2.0, 1.0, 3.0])

# 向量：表示方向或位移
v = np.array([1.0, 0.0, 0.0])

# 点沿向量方向移动 5 个单位
p_new = p + 5 * v

print("p:", p)
print("v:", v)
print("p_new:", p_new)

p: [2. 1. 3.]
v: [1. 0. 0.]
p_new: [7. 1. 3.]


## 01.04 Length, Distance, and Unit Vectors
在图形学中，单位向量非常重要，例如：

1. camera forward direction
2. light direction
3. surface normal
4. view direction
5. reflection direction

这些方向通常都需要 normalized。

In [10]:
# python implementation

def vector_length(v):
    """计算向量长度"""
    return np.sqrt(np.sum(v ** 2))


def normalize(v):
    """将非零向量单位化"""
    length = vector_length(v)

    if length == 0:
        raise ValueError("Cannot normalize a zero vector.")

    return v / length


v = np.array([3.0, 4.0, 0.0])

length = vector_length(v)
v_hat = normalize(v)

print("v:", v)
print("length:", length)
print("normalized v:", v_hat)
print("length of normalized v:", vector_length(v_hat))

v: [3. 4. 0.]
length: 5.0
normalized v: [0.6 0.8 0. ]
length of normalized v: 1.0


## 01.05 Coordinate Systems and Bases

前面我们已经讨论了：

- point：表示位置；
- vector：表示方向、位移、速度、法线；
- vector addition：连续位移；
- scalar multiplication：缩放向量；
- norm：向量长度；
- normalization：把方向向量变成单位向量。

现在进入一个更关键的问题：

同一个几何对象，为什么可以有不同的坐标表示？

在图形学中，这个问题非常重要，因为一个点或向量经常会在不同空间之间切换：

- model space；
- world space；
- view space；
- clip space；
- screen space。

例如，一个角色模型中的顶点，最开始是在 model space 中定义的。

经过 Model Matrix 后，它会进入 world space。

经过 View Matrix 后，它会进入 camera / view space。

经过 Projection Matrix 后，它会进入 clip space。

这条主线最终会变成：

$$
p_{\text{clip}}=PVMp_{\text{model}}
$$

所以，理解 coordinate system 和 basis，是理解整个图形学变换管线的前提。

### Coordinate System

一个坐标系通常由两部分组成：

1. 一个原点 origin；
2. 一组坐标轴 axes。

在 3D 空间中，一个常见坐标系包含：

- origin：O；
- x-axis；
- y-axis；
- z-axis。

在标准世界坐标系中，三个坐标轴通常写成：

$$
e_1=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

$$
e_2=
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}
$$

$$
e_3=
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix}
$$

这三个向量也叫 standard basis vectors。

任何三维向量都可以写成它们的线性组合。

### Basis

在三维空间中，如果三个向量 b1, b2, b3 满足两个条件：

1. 它们可以张成整个三维空间；
2. 它们之间线性无关；

那么它们构成一组 basis。

也就是说，任意向量 v 都可以唯一写成：

$$
v=
c_1 b_1
+
c_2 b_2
+
c_3 b_3
$$

其中：

- b1, b2, b3 是 basis vectors；
- c1, c2, c3 是 v 在这组 basis 下的 coordinates。

注意：

basis 不是坐标本身。

basis 是用来描述空间的“尺子”和“方向”。

coordinates 是某个向量在这组 basis 下的数字表示。

### Standard Basis Example

在标准基下：

$$
e_1=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

$$
e_2=
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}
$$

$$
e_3=
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix}
$$

给定向量：

$$
v=
\begin{bmatrix}
2 \\
3 \\
4
\end{bmatrix}
$$

它可以写成：

$$
v=
2e_1
+
3e_2
+
4e_3
$$

也就是：

$$
v=2
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
+
3
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}+
4
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix}=
\begin{bmatrix}
2 \\
3 \\
4
\end{bmatrix}
$$

所以在 standard basis 下，坐标：

$$
\begin{bmatrix}
2 \\
3 \\
4
\end{bmatrix}
$$

表示：

- 沿 x 轴走 2；
- 沿 y 轴走 3；
- 沿 z 轴走 4。

### Non-Standard Basis Example

现在考虑一组新的 basis：

$$
b_1=
\begin{bmatrix}
1 \\
1
\end{bmatrix}
$$

$$
b_2=
\begin{bmatrix}
1 \\
-1
\end{bmatrix}
$$

如果一个向量在这组 basis 下的坐标是：

$$
[v]_B=
\begin{bmatrix}
2 \\
3
\end{bmatrix}
$$

这不表示标准坐标中的：

$$
\begin{bmatrix}
2 \\
3
\end{bmatrix}
$$

而是表示：

$$
v=2b_1+3b_2
$$

代入：

$$
v=2
\begin{bmatrix}
1 \\
1
\end{bmatrix}
+
3
\begin{bmatrix}
1 \\
-1
\end{bmatrix}
$$

计算得到：

$$
v=
\begin{bmatrix}
2 \\
2
\end{bmatrix}+
\begin{bmatrix}
3 \\
-3
\end{bmatrix}=
\begin{bmatrix}
5 \\
-1
\end{bmatrix}
$$

所以：

$$
[v]_B=
\begin{bmatrix}
2 \\
3
\end{bmatrix}
$$

对应的 standard coordinates 是：

$$
[v]_E=
\begin{bmatrix}
5 \\
-1
\end{bmatrix}
$$

这说明：

同一个向量，在不同 basis 下，坐标可以不同。

### Basis Matrix

如果把 basis vectors 作为矩阵的列，就得到一个 basis matrix。

例如：

$$
b_1=
\begin{bmatrix}
1 \\
1
\end{bmatrix}
$$

$$
b_2=
\begin{bmatrix}
1 \\
-1
\end{bmatrix}
$$

把它们作为列向量放进矩阵：

$$
B=
\begin{bmatrix}
1 & 1 \\
1 & -1
\end{bmatrix}
$$

如果一个向量在 B 这组 basis 下的坐标是：

$$
[v]_B=
\begin{bmatrix}
2 \\
3
\end{bmatrix}
$$

那么它在 standard basis 下的坐标是：

$$
[v]_E=B[v]_B
$$

也就是：

$$
[v]_E=
\begin{bmatrix}
1 & 1 \\
1 & -1
\end{bmatrix}
\begin{bmatrix}
2 \\
3
\end{bmatrix}=
\begin{bmatrix}
5 \\
-1
\end{bmatrix}
$$

这就是 basis matrix 的核心作用：

它把某个 basis 下的坐标，转换成 standard basis 下的坐标。

### Coordinates Are Not the Vector Itself

这是本节最容易误解的地方：向量本身是几何对象,坐标只是这个几何对象在某个 basis 下的数字表示。

例如：

$$
[v]_B=
\begin{bmatrix}
2 \\
3
\end{bmatrix}
$$

和：

$$
[v]_E=
\begin{bmatrix}
5 \\
-1
\end{bmatrix}
$$

可以表示同一个几何向量。

区别在于：

- 第一组数字是在 basis B 下的坐标；
- 第二组数字是在 standard basis E 下的坐标。

所以不能脱离 basis 直接说“这个向量就是 [2, 3]”。

更准确的说法是：

```text
这个向量在某个坐标系 / basis 下的坐标是 [2, 3]。

### Core Proposition

核心命题：

如果 B 是由 basis vectors 作为列组成的矩阵，那么：

$$
[v]_E=B[v]_B
$$

其中：

- B 是 basis matrix；
- [v]_B 是向量 v 在 basis B 下的坐标；
- [v]_E 是向量 v 在 standard basis 下的坐标。

反过来，如果 B 可逆，那么：

$$
[v]_B=B^{-1}[v]_E
$$

这表示：

如果你知道一个向量在 standard basis 下的坐标，也可以通过 B 的逆矩阵，求出它在 basis B 下的坐标。

### Proof Sketch

设 basis B 由两个 basis vectors 组成：

$$
B=
\begin{bmatrix}
| & | \\
b_1 & b_2 \\
| & |
\end{bmatrix}
$$

如果向量 v 在 B 下的坐标是：

$$
[v]_B=
\begin{bmatrix}
c_1 \\
c_2
\end{bmatrix}
$$

根据 basis coordinates 的定义：

$$
v=c_1 b_1+c_2 b_2
$$

而矩阵乘法：

$$
B[v]_B=
\begin{bmatrix}
| & | \\
b_1 & b_2 \\
| & |
\end{bmatrix}
\begin{bmatrix}
c_1 \\
c_2
\end{bmatrix}
$$

根据矩阵乘法的列组合解释，结果正是：

$$
B[v]_B=c_1 b_1+c_2 b_2
$$

所以：

$$
[v]_E=B[v]_B
$$

这说明 basis matrix 乘坐标向量，本质上是在做 basis vectors 的线性组合。

In [11]:
# Numpy Implementation

# basis vectors
b1 = np.array([1.0, 1.0])
b2 = np.array([1.0, -1.0])

# 把 basis vectors 作为列，组成 basis matrix
B = np.column_stack([b1, b2])

# v 在 basis B 下的坐标
v_B = np.array([2.0, 3.0])

# 转换到 standard basis 下
v_E = B @ v_B

print("Basis matrix B:")
print(B)

print("Coordinates in basis B:")
print(v_B)

print("Coordinates in standard basis E:")
print(v_E)

Basis matrix B:
[[ 1.  1.]
 [ 1. -1.]]
Coordinates in basis B:
[2. 3.]
Coordinates in standard basis E:
[ 5. -1.]


In [13]:
# standard coordinates
v_E = np.array([5.0, -1.0])

# 求 v 在 basis B 下的坐标
v_B = np.linalg.inv(B) @ v_E

print("Coordinates in standard basis E:")
print(v_E)

print("Coordinates in basis B:")
print(v_B)

Coordinates in standard basis E:
[ 5. -1.]
Coordinates in basis B:
[2. 3.]


### Graphics Application

basis 在图形学中非常常见。

例如，一个物体有自己的 local coordinate system：

- local right direction；
- local up direction；
- local forward direction。

这三个方向可以组成模型自己的 basis。

如果一个点在 local space 下的坐标是：

$$
p_{\text{local}}=
\begin{bmatrix}
2 \\
1 \\
3
\end{bmatrix}
$$

这表示：

- 沿 local right 方向走 2；
- 沿 local up 方向走 1；
- 沿 local forward 方向走 3。

如果这个物体的三个 local axes 在 world space 中分别是：

$$
r=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

$$
u=
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}
$$

$$
f=
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix}
$$

那么 basis matrix 是：

$$
B=
\begin{bmatrix}
| & | & | \\
r & u & f \\
| & | & |
\end{bmatrix}
$$

local point 转换到 world direction / displacement 时，可以写成：

$$
p_{\text{world}}=
B p_{\text{local}}
$$

如果还要考虑物体在 world space 中的位置，也就是 translation，就需要 affine transformation 和 homogeneous coordinates。

这会在后面的章节中展开。

### Exercises

#### Exercise 1: Standard Basis

给定 standard basis：

$$
e_1=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

$$
e_2=
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}
$$

$$
e_3=
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix}
$$

给定向量：

$$
v=
\begin{bmatrix}
3 \\
-2 \\
5
\end{bmatrix}
$$

请把 v 写成：

$$
v=
c_1e_1
+
c_2e_2
+
c_3e_3
$$

并写出 c1, c2, c3。

#### Exercise 2: Non-Standard Basis

给定：

$$
b_1=
\begin{bmatrix}
2 \\
0
\end{bmatrix}
$$

$$
b_2=
\begin{bmatrix}
0 \\
3
\end{bmatrix}
$$

一个向量在 basis B 下的坐标是：

$$
[v]_B=
\begin{bmatrix}
4 \\
5
\end{bmatrix}
$$

求它在 standard basis 下的坐标：

$$
[v]_E
$$

#### Exercise 3: Basis Matrix

给定：

$$
b_1=
\begin{bmatrix}
1 \\
1
\end{bmatrix}
$$

$$
b_2=
\begin{bmatrix}
2 \\
0
\end{bmatrix}
$$

请构造 basis matrix：

$$
B=
\begin{bmatrix}
| & | \\
b_1 & b_2 \\
| & |
\end{bmatrix}
$$

然后计算：

$$
[v]_E=
B[v]_B
$$

其中：

$$
[v]_B=
\begin{bmatrix}
3 \\
2
\end{bmatrix}
$$

#### Exercise 4: Inverse Coordinates

给定 basis matrix：

$$
B=
\begin{bmatrix}
1 & 1 \\
1 & -1
\end{bmatrix}
$$

已知某个向量在 standard basis 下的坐标为：

$$
[v]_E=
\begin{bmatrix}
6 \\
2
\end{bmatrix}
$$

求它在 basis B 下的坐标：

$$
[v]_B
$$

也就是求解：

$$
B[v]_B=[v]_E
$$

#### Exercise 5: Graphics Interpretation

一个物体的 local coordinate system 中有三个方向：

$$
r=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

$$
u=
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}
$$

$$
f=
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix}
$$

local point 是：

$$
p_{\text{local}}=
\begin{bmatrix}
2 \\
3 \\
4
\end{bmatrix}
$$

请解释：

$$
p_{\text{local}}=
\begin{bmatrix}
2 \\
3 \\
4
\end{bmatrix}
$$

在几何上是什么意思。

也就是说：

- 2 表示沿哪个方向走？
- 3 表示沿哪个方向走？
- 4 表示沿哪个方向走？

#### Exercise 6: NumPy Practice

用 NumPy 实现以下操作：

1. 用 `np.column_stack()` 构造 basis matrix B；
2. 给定 `[v]_B`，计算 `[v]_E = B @ [v]_B`；
3. 给定 `[v]_E`，用 `np.linalg.solve(B, v_E)` 反解 `[v]_B`；
4. 验证反解结果是否和原来的 `[v]_B` 一致。

## 01.06 Local Space and World Space

上一节我们讲了 coordinate system 和 basis。这一节开始把它放进图形学语境中。在图形学中，一个顶点的坐标通常不是一开始就直接写在 world space 中的。

更常见的情况是：

- 模型文件中的顶点坐标定义在 model space / local space 中；
- 游戏或渲染引擎把这个模型放到 world space 中；
- 后续相机会把 world space 再变换到 view space；
- 投影矩阵再把 view space 变换到 clip space。

最终主线是：

$$
p_{\text{clip}}=
PVMp_{\text{model}}
$$

这一节先只关注其中第一步：

$$
p_{\text{world}}=
Mp_{\text{model}}
$$

不过在正式使用 4D homogeneous coordinates 和 Model Matrix 之前，我们先用 3D 向量形式理解 local space 到 world space 的几何含义。

### Graphics Motivation

假设你在 Blender、Maya 或其他建模软件中创建了一个 cube。这个 cube 的顶点坐标通常是围绕模型自己的原点定义的。例如一个顶点在 model space 中是：

$$
p_{\text{local}}=
\begin{bmatrix}
1 \\
1 \\
1
\end{bmatrix}
$$

这表示：

在模型自己的坐标系中，这个点位于：

- local x 方向 1 个单位；
- local y 方向 1 个单位；
- local z 方向 1 个单位。

但是在游戏世界中，这个 cube 可能被放在：

$$
o_{\text{world}}=
\begin{bmatrix}
10 \\
0 \\
5
\end{bmatrix}
$$

这时，模型自身的坐标和世界坐标不是一回事。

因此我们需要理解：

```text
local space：物体自己的坐标系
world space：整个场景共享的坐标系

### Local Space

Local space 也叫 model space。

它是模型自己的坐标系。

例如一个角色模型有自己的：

- local origin；
- local right direction；
- local up direction；
- local forward direction。

模型顶点最开始通常都定义在这个 local space 中。

例如：

$$
p_{\text{local}}=
\begin{bmatrix}
2 \\
1 \\
3
\end{bmatrix}
$$

这不表示它在世界中的绝对位置。

它只表示：

在模型自己的坐标系中：

- 沿 local right 方向走 2；
- 沿 local up 方向走 1；
- 沿 local forward 方向走 3。

所以 local coordinates 是相对于模型自身而言的坐标。

### World Space

World space 是整个场景共享的坐标系。

场景中的所有对象、相机、光源，最终都需要放到同一个 world space 中进行组织。

例如：

- 一棵树的位置；
- 一个角色的位置；
- 一盏灯的位置；
- 相机的位置；
- 地面的坐标；
- 物体之间的相对距离；

这些通常都在 world space 中描述。

如果一个模型的 world origin 是：

$$
o_{\text{world}}=
\begin{bmatrix}
10 \\
0 \\
5
\end{bmatrix}
$$

这表示：

模型的 local origin 被放到了世界坐标：

$$
\begin{bmatrix}
10 \\
0 \\
5
\end{bmatrix}
$$

处。

### Local Axes Expressed in World Space

一个物体在 world space 中不仅有位置，还有朝向。

朝向可以用三个 local axes 在 world space 中的方向表示：

$$
r=
\begin{bmatrix}
r_x \\
r_y \\
r_z
\end{bmatrix}
$$

$$
u=
\begin{bmatrix}
u_x \\
u_y \\
u_z
\end{bmatrix}
$$

$$
f=
\begin{bmatrix}
f_x \\
f_y \\
f_z
\end{bmatrix}
$$

其中：

- r 表示 local right direction 在 world space 中的方向；
- u 表示 local up direction 在 world space 中的方向；
- f 表示 local forward direction 在 world space 中的方向。

把它们作为列向量放进矩阵：

$$
B=
\begin{bmatrix}
| & | & | \\
r & u & f \\
| & | & |
\end{bmatrix}
$$

这个矩阵描述了：

```text
local basis 在 world space 中长什么样

### From Local Coordinates to World Coordinates

如果一个点在 local space 中的坐标是：

$$
p_{\text{local}}=
\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}
$$

并且物体的 local axes 在 world space 中分别是：

$$
r,u,f
$$

那么这个点相对于物体原点的 world displacement 是：

$$
Bp_{\text{local}}=xr+yu+zf
$$

如果物体的 local origin 在 world space 中的位置是：

$$
o_{\text{world}}
$$

那么点的 world coordinates 是：

$$
p_{\text{world}}=o_{\text{world}}+Bp_{\text{local}}
$$

这就是 local space 到 world space 的核心公式。

其中：

- p_local 是点在 local space 中的坐标；
- B 是由 local axes 组成的 basis matrix；
- o_world 是模型原点在 world space 中的位置；
- p_world 是该点在 world space 中的坐标。

### Concrete Example Without Rotation

先看最简单的情况。

假设模型没有旋转，它的 local axes 和 world axes 完全一致：

$$
r=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

$$
u=
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}
$$

$$
f=
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix}
$$

所以：

$$
B=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

模型原点在 world space 中是：

$$
o_{\text{world}}=
\begin{bmatrix}
10 \\
0 \\
5
\end{bmatrix}
$$

local point 是：

$$
p_{\text{local}}=
\begin{bmatrix}
2 \\
1 \\
3
\end{bmatrix}
$$

则：

$$
p_{\text{world}}=
o_{\text{world}}
+
Bp_{\text{local}}
$$

因为 B 是单位矩阵，所以：

$$
Bp_{\text{local}}=
p_{\text{local}}
$$

因此：

$$
p_{\text{world}}=
\begin{bmatrix}
10 \\
0 \\
5
\end{bmatrix}+
\begin{bmatrix}
2 \\
1 \\
3
\end{bmatrix}=
\begin{bmatrix}
12 \\
1 \\
8
\end{bmatrix}
$$

这表示：

模型自身的点：

$$
\begin{bmatrix}
2 \\
1 \\
3
\end{bmatrix}
$$

被放到世界中后，变成了：

$$
\begin{bmatrix}
12 \\
1 \\
8
\end{bmatrix}
$$

### Concrete Example With Rotation

现在考虑物体发生了旋转。

假设物体的 local axes 在 world space 中变成：

$$
r=
\begin{bmatrix}
0 \\
0 \\
-1
\end{bmatrix}
$$

$$
u=
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}
$$

$$
f=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

这表示：

- local right 方向对应 world negative z；
- local up 方向仍然对应 world positive y；
- local forward 方向对应 world positive x。

basis matrix 是：

$$
B=
\begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
-1 & 0 & 0
\end{bmatrix}
$$

设：

$$
p_{\text{local}}=
\begin{bmatrix}
2 \\
1 \\
3
\end{bmatrix}
$$

那么：

$$
Bp_{\text{local}}=
2r
+
1u
+
3f
$$

代入：

$$
Bp_{\text{local}}=
2
\begin{bmatrix}
0 \\
0 \\
-1
\end{bmatrix}+
1
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}+
3
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

所以：

$$
Bp_{\text{local}}=
\begin{bmatrix}
3 \\
1 \\
-2
\end{bmatrix}
$$

如果模型原点在 world space 中是：

$$
o_{\text{world}}=
\begin{bmatrix}
10 \\
0 \\
5
\end{bmatrix}
$$

那么：

$$
p_{\text{world}}=
o_{\text{world}}+
Bp_{\text{local}}
$$

即：

$$
p_{\text{world}}=
\begin{bmatrix}
10 \\
0 \\
5
\end{bmatrix}+
\begin{bmatrix}
3 \\
1 \\
-2
\end{bmatrix}=
\begin{bmatrix}
13 \\
1 \\
3
\end{bmatrix}
$$

这个例子说明：

local coordinates 不是直接加到 world coordinates 上。

必须先根据物体的 local axes，把 local displacement 转换成 world displacement。

### Points and Vectors Transform Differently

local point 到 world point 的公式是：

$$
p_{\text{world}}=o_{\text{world}}+Bp_{\text{local}}
$$

但是 local vector 到 world vector 的公式是：

$$
v_{\text{world}}=Bv_{\text{local}}
$$

注意：vector 不需要加 origin。

原因是：

- point 表示位置；
- vector 表示方向或位移。

物体的位置会影响点的 world coordinates。

但物体的位置不应该影响方向向量。

例如，一个角色向前看的方向只和角色朝向有关，不和角色站在哪里有关。

所以：

```text
point transformation: basis transformation + translation
vector transformation: basis transformation only

### Core Proposition

核心命题：

如果一个物体的 local axes 在 world space 中组成 basis matrix B，并且 local origin 在 world space 中的位置是 o_world，那么：

点的变换是：

$$
p_{\text{world}}=o_{\text{world}}+Bp_{\text{local}}
$$

向量的变换是：

$$
v_{\text{world}}=Bv_{\text{local}}
$$

区别在于点需要加 translation，向量不需要加 translation。

这个差异是后面 homogeneous coordinates 的理论基础。

### Proof Sketch

设 local point 的坐标是：

$$
p_{\text{local}}=\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}
$$

这表示该点相对于 local origin 的位移为：

$$
xr+yu+zf
$$

其中：

- r 是 local x-axis 在 world space 中的方向；
- u 是 local y-axis 在 world space 中的方向；
- f 是 local z-axis 在 world space 中的方向。

把 r, u, f 作为列向量组成矩阵 B：

$$
B=
\begin{bmatrix}
| & | & | \\
r & u & f \\
| & | & |
\end{bmatrix}
$$

根据矩阵乘法的列组合解释：

$$
Bp_{\text{local}}=xr+yu+zf
$$

这是从 local origin 出发的 world displacement。

如果 local origin 本身在 world space 中的位置是：

$$
o_{\text{world}}
$$

那么点的最终 world position 就是：

$$
p_{\text{world}}=o_{\text{world}}+Bp_{\text{local}}
$$

对于向量来说，它本身就是 displacement，不依赖 origin。

所以：

$$
v_{\text{world}}=Bv_{\text{local}}
$$

In [ ]:
# local axes expressed in world space
r = np.array([0.0, 0.0, -1.0])
u = np.array([0.0, 1.0, 0.0])
f = np.array([1.0, 0.0, 0.0])

# basis matrix: columns are local axes
B = np.column_stack([r, u, f])

# local origin in world space
o_world = np.array([10.0, 0.0, 5.0])

# local point
p_local = np.array([2.0, 1.0, 3.0])

# local vector
v_local = np.array([2.0, 1.0, 3.0])

# point transformation
p_world = o_world + B @ p_local

# vector transformation
v_world = B @ v_local

print("Basis matrix B:")
print(B)

print("p_world:")
print(p_world)

print("v_world:")
print(v_world)

Basis matrix B:
[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]
p_world:
[13.  1.  3.]
v_world:
[ 3.  1. -2.]


### NumPy Implementation

下面的代码验证：

$$
p_{\text{world}}=o_{\text{world}}+Bp_{\text{local}}
$$

以及：

$$
v_{\text{world}}=Bv_{\text{local}}
$$

注意同样的 local 数值下：

$$
\begin{bmatrix}
2 \\
1 \\
3
\end{bmatrix}
$$

如果解释为 point，需要加 origin。如果解释为 vector，不需要加 origin。

In [2]:
def local_point_to_world(p_local, origin_world, basis):
    """Convert a local point to a world point."""
    return origin_world + basis @ p_local


def local_vector_to_world(v_local, basis):
    """Convert a local vector to a world vector."""
    return basis @ v_local


r = np.array([0.0, 0.0, -1.0])
u = np.array([0.0, 1.0, 0.0])
f = np.array([1.0, 0.0, 0.0])

B = np.column_stack([r, u, f])

origin_world = np.array([10.0, 0.0, 5.0])

p_local = np.array([2.0, 1.0, 3.0])
v_local = np.array([2.0, 1.0, 3.0])

p_world = local_point_to_world(p_local, origin_world, B)
v_world = local_vector_to_world(v_local, B)

print("world point:", p_world)
print("world vector:", v_world)

world point: [13.  1.  3.]
world vector: [ 3.  1. -2.]


### Graphics Application

Local space 和 world space 的区别贯穿整个图形学管线。

一个模型的顶点数据通常存储在 local space 中。

例如：

$$
p_{\text{model}}=
\begin{bmatrix}
2 \\
1 \\
3
\end{bmatrix}
$$

当游戏引擎把模型放到场景中时，需要指定：

- 模型在世界中的位置；
- 模型在世界中的朝向；
- 模型在世界中的缩放。

这些信息组合起来，就是后面会讲的 Model Matrix。

在更完整的形式中，local point 到 world point 会写成：

$$
p_{\text{world}}=
Mp_{\text{model}}
$$

如果继续经过相机和投影，就得到：

$$
p_{\text{clip}}=
PVMp_{\text{model}}
$$

所以本节公式：

$$
p_{\text{world}}=o_{\text{world}}+Bp_{\text{local}}
$$

可以看作 Model Matrix 的前置版本。

它已经包含了两个核心部分：

- B：描述 orientation / basis；
- o_world：描述 translation。

下一阶段用 homogeneous coordinates 后，这两部分会被统一写进一个 4 × 4 矩阵。

### Exercises

#### Exercise 1: Local Point Without Rotation

假设模型没有旋转。

local axes 和 world axes 完全一致：

$$
B=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

模型原点在 world space 中是：

$$
o_{\text{world}}=
\begin{bmatrix}
5 \\
2 \\
-1
\end{bmatrix}
$$

local point 是：

$$
p_{\text{local}}=
\begin{bmatrix}
3 \\
4 \\
2
\end{bmatrix}
$$

求：

$$
p_{\text{world}}=o_{\text{world}}+Bp_{\text{local}}
$$

#### Exercise 2: Local Vector Without Rotation

沿用 Exercise 1 中的 basis matrix：

$$
B=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

给定 local vector：

$$
v_{\text{local}}=
\begin{bmatrix}
3 \\
4 \\
2
\end{bmatrix}
$$

求：

$$
v_{\text{world}}=
Bv_{\text{local}}
$$

并解释为什么这里不需要加：

$$
o_{\text{world}}
$$

#### Exercise 3: Local Point With Rotation

给定 local axes 在 world space 中为：

$$
r=
\begin{bmatrix}
0 \\
0 \\
-1
\end{bmatrix}
$$

$$
u=
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}
$$

$$
f=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

所以：

$$
B=
\begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
-1 & 0 & 0
\end{bmatrix}
$$

模型原点在 world space 中是：

$$
o_{\text{world}}=
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}
$$

local point 是：

$$
p_{\text{local}}=
\begin{bmatrix}
4 \\
5 \\
6
\end{bmatrix}
$$

求：

$$
p_{\text{world}}=o_{\text{world}}+Bp_{\text{local}}
$$

#### Exercise 4: Local Vector With Rotation

沿用 Exercise 3 的 basis matrix：

$$
B=
\begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
-1 & 0 & 0
\end{bmatrix}
$$

给定 local vector：

$$
v_{\text{local}}=
\begin{bmatrix}
4 \\
5 \\
6
\end{bmatrix}
$$

求：

$$
v_{\text{world}}=
Bv_{\text{local}}
$$

并比较它和 Exercise 3 中 point transformation 的区别。

#### Exercise 5: Point or Vector?

判断下面对象更应该被视为 point 还是 vector：

1. 一个角色的位置；
2. 从角色指向敌人的方向；
3. 一束平行光的方向；
4. 一个 mesh vertex 的位置；
5. 一个 surface normal；
6. 相机的位置；
7. 相机的 forward direction；
8. 两个点之间的 displacement。

并说明它们在 local-to-world transformation 中是否应该受到 translation 影响。

## 01.07 Graphics Application: Moving a Point in 3D Space

前面我们已经学习了：

- point 表示位置；
- vector 表示方向或位移；
- 单位向量表示纯方向；
- speed 表示单位时间移动距离；
- delta time 表示每一帧经过的时间；
- local space 和 world space 表示不同坐标系。

这一节把它们组合起来，形成一个非常基础的游戏移动公式：

$$
p_{\text{new}}=p+\Delta t \cdot s \cdot \hat d
$$

其中：

- p 是当前点的位置；
- d_hat 是单位方向向量；
- s 是速度；
- Δt 是时间步长；
- p_new 是移动后的新位置。

这就是很多游戏中角色、相机、子弹、物体移动的基础形式。

### Graphics Motivation

假设一个角色当前在 world space 中的位置是：

$$
p=
\begin{bmatrix}
0 \\
0 \\
0
\end{bmatrix}
$$

角色希望沿 world x 方向移动。

移动方向是：

$$
d=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

如果角色速度是：

```text
speed = 2 units / second
```

每一帧时间间隔是：

```text
delta_time = 0.5 seconds
```

那么这一帧角色应该移动：

$$
\Delta p=speed \cdot delta\_time \cdot d
$$

代入：

$$
\Delta p=2\cdot 0.5 \cdot
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

所以新位置是：

$$
p_{\text{new}}=
\begin{bmatrix}
0 \\
0 \\
0
\end{bmatrix}+
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

### Movement Formula

最基本的移动公式是：

$$
p_{\text{new}}=p+v
$$

其中：

- p 是当前位置；
- v 是位移向量；
- p_new 是新位置。

如果位移来自方向、速度和时间，那么：

$$
v=\Delta t \cdot s \cdot \hat d
$$

所以：

$$
p_{\text{new}}=p+\Delta t \cdot s \cdot \hat d
$$

这里要注意：

d_hat 必须是单位向量。如果 d_hat 不是单位向量，那么 speed 的含义就会被破坏。

### Why Direction Should Be Normalized

假设速度是：

```text
speed = 2
```

方向向量是：

$$
d=
\begin{bmatrix}
3 \\
4 \\
0
\end{bmatrix}
$$

这个方向向量的长度是：

$$
\|d\|=5
$$

如果直接使用：

$$
p_{\text{new}}=p+\Delta t \cdot s \cdot d
$$

那么实际移动距离会被 d 的长度放大 5 倍。

所以在移动公式中，通常应该先做 normalization：

$$
\hat d=\frac{d}{\|d\|}
$$

然后使用：

$$
p_{\text{new}}=p+\Delta t \cdot s \cdot \hat d
$$

这样 speed 才真正表示单位时间移动距离。

### Concrete Example

给定当前位置：

$$
p=
\begin{bmatrix}
0 \\
0 \\
0
\end{bmatrix}
$$

给定方向向量：

$$
d=
\begin{bmatrix}
3 \\
4 \\
0
\end{bmatrix}
$$

它的长度是：

$$
\|d\|=5
$$

单位方向是：

$$
\hat d=
\begin{bmatrix}
0.6 \\
0.8 \\
0
\end{bmatrix}
$$

设速度为：

```text
speed = 10
```

时间步长为：

```text
delta_time = 0.2
```

那么移动距离是：

$$
speed \cdot delta\_time=10 \cdot 0.2=2
$$

新位置为：

$$
p_{\text{new}}=p+2\hat d
$$

所以：

$$
p_{\text{new}}=
\begin{bmatrix}
0 \\
0 \\
0
\end{bmatrix}+2
\begin{bmatrix}
0.6 \\
0.8 \\
0
\end{bmatrix}=
\begin{bmatrix}
1.2 \\
1.6 \\
0
\end{bmatrix}
$$

### NumPy Implementation: Basic Movement

下面用 NumPy 实现最基本的移动逻辑：

$$
p_{\text{new}}=p+\Delta t \cdot s \cdot \hat d
$$

其中：

- `p` 是当前位置；
- `direction` 是输入方向；
- `speed` 是速度；
- `delta_time` 是时间步长；
- `direction_hat` 是单位方向；
- `p_new` 是新位置。

In [5]:
# def vector_length(v: np.ndarray) -> float:
#     """Return the Euclidean length of a vector."""
#     return float(np.sqrt(np.sum(v ** 2)))


# def normalize(v: np.ndarray) -> np.ndarray:
#     """Return the unit vector in the same direction as v."""
#     length = vector_length(v)
#     if length == 0:
#         raise ValueError("Cannot normalize a zero vector.")
#     return v / length


p = np.array([0.0, 0.0, 0.0])
direction = np.array([3.0, 4.0, 0.0])

speed = 10.0
delta_time = 0.2

direction_hat = normalize(direction)
p_new = p + delta_time * speed * direction_hat

print("direction_hat:", direction_hat)
print("p_new:", p_new)

direction_hat: [0.6 0.8 0. ]
p_new: [1.2 1.6 0. ]


### Function: move_point

可以把移动逻辑封装成函数：

$$
p_{\text{new}}=p+\Delta t \cdot s \cdot \hat d
$$

这个函数接收：

- point；
- direction；
- speed；
- delta_time；

返回移动后的新 point。

注意：direction 会在函数内部被 normalized。

In [6]:
def move_point(
    p: np.ndarray,
    direction: np.ndarray,
    speed: float,
    delta_time: float,
) -> np.ndarray:
    """Move a point along a direction with speed and delta time."""
    direction_hat = normalize(direction)
    return p + delta_time * speed * direction_hat


p = np.array([0.0, 0.0, 0.0])
direction = np.array([3.0, 4.0, 0.0])

p_new = move_point(
    p=p,
    direction=direction,
    speed=10.0,
    delta_time=0.2,
)

print("p_new:", p_new)

p_new: [1.2 1.6 0. ]


### Frame-Rate Independence

在游戏中，帧率可能变化。如果每一帧都简单写：

$$
p_{\text{new}}=p+\hat d
$$

那么高帧率机器上，每秒移动次数更多，角色会移动得更快。

为了避免这个问题，移动公式必须乘以 delta_time：

$$
p_{\text{new}}=p+\Delta t \cdot s \cdot \hat d
$$

这样无论一秒钟更新 30 帧、60 帧还是 120 帧，只要总时间相同，理论上的移动距离就一致。这叫 frame-rate independent movement。

### NumPy Simulation: Different Frame Rates

下面模拟同一个角色移动 1 秒。

速度为：

```text
speed = 2 units / second
```

方向为：

$$
d=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

如果总时间都是 1 秒，那么不管分成 10 帧、30 帧还是 60 帧，最终位置都应该接近：

$$
p_{\text{final}}=
\begin{bmatrix}
2 \\
0 \\
0
\end{bmatrix}
$$

In [7]:
def simulate_movement(
    num_frames: int,
    total_time: float,
    speed: float,
    direction: np.ndarray,
) -> np.ndarray:
    """Simulate frame-rate independent movement."""
    p = np.array([0.0, 0.0, 0.0])
    delta_time = total_time / num_frames

    for _ in range(num_frames):
        p = move_point(
            p=p,
            direction=direction,
            speed=speed,
            delta_time=delta_time,
        )

    return p


direction = np.array([1.0, 0.0, 0.0])
speed = 2.0
total_time = 1.0

for num_frames in [10, 30, 60, 120]:
    p_final = simulate_movement(
        num_frames=num_frames,
        total_time=total_time,
        speed=speed,
        direction=direction,
    )
    print(f"{num_frames} frames:", p_final)

10 frames: [2. 0. 0.]
30 frames: [2. 0. 0.]
60 frames: [2. 0. 0.]
120 frames: [2. 0. 0.]


### Local Direction and World Movement

在真实游戏中，输入方向通常是 local direction。

例如：

```text
按 W：沿角色自己的 forward 方向移动
按 D：沿角色自己的 right 方向移动
```

但角色真正的位置是在 world space 中更新的。

所以需要先把 local movement direction 转换成 world direction：

$$
d_{\text{world}}=B d_{\text{local}}
$$

然后再更新 world position：

$$
p_{\text{world,new}}=p_{\text{world}}+\Delta t \cdot s \cdot \hat d_{\text{world}}
$$

其中：

- B 是角色 local axes 在 world space 中组成的 basis matrix；
- d_local 是输入方向；
- d_world 是世界空间中的移动方向。

### Concrete Example: Move Along Local Forward

假设角色的 local axes 在 world space 中是：

$$
r=
\begin{bmatrix}
0 \\
0 \\
-1
\end{bmatrix}
$$

$$
u=
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}
$$

$$
f=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

所以：

$$
B=
\begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
-1 & 0 & 0
\end{bmatrix}
$$

如果玩家按 W，表示沿 local forward 移动：

$$
d_{\text{local}}=
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix}
$$

那么 world direction 是：

$$
d_{\text{world}}=B d_{\text{local}}=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

这说明：

虽然玩家输入的是 local forward，但因为角色已经旋转，所以它在 world space 中实际上沿 world x 方向移动。

### NumPy Implementation: Local Direction to World Movement

下面实现：

$$
d_{\text{world}}=B d_{\text{local}}
$$

以及：

$$
p_{\text{world,new}}=p_{\text{world}}+\Delta t \cdot s \cdot \hat d_{\text{world}}
$$

In [8]:
r = np.array([0.0, 0.0, -1.0])
u = np.array([0.0, 1.0, 0.0])
f = np.array([1.0, 0.0, 0.0])

B = np.column_stack([r, u, f])

p_world = np.array([10.0, 0.0, 5.0])

d_local = np.array([0.0, 0.0, 1.0])
d_world = B @ d_local

p_world_new = move_point(
    p=p_world,
    direction=d_world,
    speed=4.0,
    delta_time=0.5,
)

print("B:")
print(B)

print("d_world:", d_world)
print("p_world_new:", p_world_new)

B:
[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]
d_world: [1. 0. 0.]
p_world_new: [12.  0.  5.]


### Multiple Input Directions

游戏角色经常会同时接收多个输入。

例如：

```text
W：forward
D：right
```

如果同时按 W 和 D，local movement direction 可以写成：

$$
d_{\text{local}}=
\begin{bmatrix}
1 \\
0 \\
1
\end{bmatrix}
$$

这里的含义是：

- local right 方向有 1；
- local up 方向有 0；
- local forward 方向有 1。

但是这个向量长度不是 1。它的长度是：

$$
\|d_{\text{local}}\|=\sqrt{2}
$$

如果不 normalize，对角移动会比直线移动更快。所以组合输入方向后，应该先 normalization，再参与移动计算。

### Diagonal Movement Problem

如果玩家只按 W：

$$
d_{\text{local}}=
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix}
$$

长度为：

$$
\|d_{\text{local}}\|=1
$$

如果玩家同时按 W 和 D：

$$
d_{\text{local}}=
\begin{bmatrix}
1 \\
0 \\
1
\end{bmatrix}
$$

长度为：

$$
\|d_{\text{local}}\|=\sqrt{2}
$$

如果直接使用这个方向移动，角色会以更快速度斜向移动。

所以应该使用：

$$
\hat d_{\text{local}}=\frac{d_{\text{local}}}{\|d_{\text{local}}\|}
$$

再转换到 world space。

### Exercises

#### Exercise 1: Basic Movement

给定当前位置：

$$
p=
\begin{bmatrix}
0 \\
0 \\
0
\end{bmatrix}
$$

移动方向：

$$
d=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

速度：

```text
speed = 3
```

时间步长：

```text
delta_time = 2
```

计算：

$$
p_{\text{new}}=p+\Delta t \cdot s \cdot \hat d
$$

#### Exercise 2: Normalize Before Moving

给定当前位置：

$$
p=
\begin{bmatrix}
0 \\
0 \\
0
\end{bmatrix}
$$

移动方向：

$$
d=
\begin{bmatrix}
0 \\
3 \\
4
\end{bmatrix}
$$

速度：

```text
speed = 10
```

时间步长：

```text
delta_time = 0.5
```

先求单位方向：

$$
\hat d=\frac{d}{\|d\|}
$$

再计算：

$$
p_{\text{new}}=p+\Delta t \cdot s \cdot \hat d
$$

#### Exercise 3: Frame-Rate Independence

角色沿 x 方向移动：

$$
d=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

速度为：

```text
speed = 6 units / second
```

总时间为：

```text
total_time = 2 seconds
```

分别模拟：

```text
20 frames
60 frames
120 frames
```

要求每种情况下都使用：

$$
delta\_time=\frac{total\_time}{num\_frames}
$$

验证最终位置是否一致。

#### Exercise 4: Local Forward Movement

给定 local axes 在 world space 中为：

$$
r=
\begin{bmatrix}
0 \\
0 \\
-1
\end{bmatrix}
$$

$$
u=
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}
$$

$$
f=
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

basis matrix 为：

$$
B=
\begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
-1 & 0 & 0
\end{bmatrix}
$$

当前 world position 是：

$$
p_{\text{world}}=
\begin{bmatrix}
10 \\
0 \\
5
\end{bmatrix}
$$

玩家按 W，local direction 是：

$$
d_{\text{local}}=
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix}
$$

速度为：

```text
speed = 4
```

时间步长为：

```text
delta_time = 0.5
```

先计算：

$$
d_{\text{world}}=B d_{\text{local}}
$$

再计算：

$$
p_{\text{world,new}}=p_{\text{world}}+\Delta t \cdot s \cdot \hat d_{\text{world}}
$$

#### Exercise 5: Diagonal Movement

玩家同时按 W 和 D。

local direction 是：

$$
d_{\text{local}}=
\begin{bmatrix}
1 \\
0 \\
1
\end{bmatrix}
$$

请计算：

1. d_local 的长度；
2. d_local 的单位向量；
3. 如果 speed = 5，delta_time = 1，不 normalize 时移动距离是多少；
4. normalize 后移动距离是多少；
5. 为什么游戏中通常需要 normalize diagonal input。

## Summary Table

| Concept | Correct Interpretation | Common Mistake |
|---|---|---|
| point | position | treating it exactly like a vector |
| vector | direction / displacement | adding translation to it |
| coordinates | numbers under a basis | treating coordinates as the object itself |
| basis matrix | columns are basis vectors | putting basis vectors in rows |
| local space | object's own coordinate system | treating it as world space |
| world space | shared scene coordinate system | ignoring object transformation |
| direction | should often be normalized | speed affected by vector length |
| zero vector | cannot be normalized | division by zero |
| matrix multiplication | use `@` in NumPy | using `*` |
| transformation order | right to left under column vectors | reading left to right |
| translation | affine, not linear in 3D | treating it as ordinary linear map |